package exception.runtime.test;

public class RuntimeExceptionTest01 {
    public static void main(String[] args) {
        //Erros do programador
        int[] nums = {1, 2};
        System.out.println(nums[2]);
    }
}
